# Generated by Django 3.2.9 on 2021-12-22 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Secretaria (Exemplo: Administraçao, Governo, etc .).', max_length=200, verbose_name='Nome da Secretaria')),
                ('excluido', models.BooleanField(default=False, verbose_name='Excluído')),
                ('desativado', models.BooleanField(default=False)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_usuario_turma', to=settings.AUTH_USER_MODEL, verbose_name='Servidor Responsavel')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'permissions': (('baseapp_add_turma', 'Adicionar Secretaria'), ('baseapp_detail_turma', 'Visualizar Secretaria'), ('baseapp_delete_turma', 'Excluir Secretaria')),
            },
        ),
    ]
