# Generated by Django 3.2.9 on 2021-12-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaapp', '0009_auto_20211222_1047'),
        ('baseapp', '0002_turma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
