# Generated by Django 3.2.9 on 2021-12-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='turmas',
            field=models.CharField(choices=[(1, '1° Prêmio'), (2, '2° Prêmio'), (3, '3° Prêmio'), (4, '4° Prêmio'), (5, '5° Prêmio')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
