# Generated by Django 3.2.9 on 2021-12-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaapp', '0002_crianca_turmas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crianca',
            old_name='turmas',
            new_name='turma',
        ),
    ]
