# Generated by Django 3.2.9 on 2021-12-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaapp', '0005_remove_crianca_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='turma',
            field=models.CharField(blank=True, choices=[(1, 'Bercario 1'), (2, 'Bercario 2'), (3, 'Maternal'), (4, 'Jardim'), (5, 'Pré'), (6, 'FIC')], max_length=1, null=True),
        ),
    ]
