# Generated by Django 3.2.9 on 2021-12-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaapp', '0006_crianca_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='turma',
        ),
    ]
