# Generated by Django 3.2.9 on 2021-12-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_turma'),
        ('listaapp', '0007_remove_crianca_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='turma',
            field=models.ForeignKey(help_text='Turma definida .', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.turma', verbose_name='Turma'),
        ),
    ]
