# Generated by Django 3.2.9 on 2022-01-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listaapp', '0009_auto_20211222_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='cei',
        ),
        migrations.AddField(
            model_name='crianca',
            name='cei',
            field=models.ManyToManyField(help_text='Cei desejado .', null=True, to='listaapp.Cei', verbose_name='Cei'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='turma',
            field=models.ForeignKey(blank=True, help_text='Turma definida .', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listaapp.turma', verbose_name='Turma'),
        ),
    ]
