# Generated by Django 3.2.9 on 2022-01-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaapp', '0010_auto_20220110_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='cpf',
            field=models.CharField(default=1, max_length=200, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
