# Generated by Django 3.2.9 on 2021-11-30 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='usuario/imagem')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de Contato.', max_length=15, null=True, verbose_name='Telefone')),
                ('obs', models.TextField(blank=True, help_text='Telefone de Contato.', max_length=200, null=True, verbose_name='Observação')),
                ('excluido', models.BooleanField(default=False, verbose_name='Excluído')),
                ('desativado', models.BooleanField(default=False)),
                ('propriedade', models.ManyToManyField(blank=True, related_name='ususario_propriedade', to='baseapp.Propriedade')),
                ('setor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_setor', to='baseapp.setor', verbose_name='Setor')),
                ('user', models.OneToOneField(help_text='Deve conter o usuário.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_user', to=settings.AUTH_USER_MODEL, verbose_name='ID do Usuário (Auth User)')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'permissions': (('baseapp_add_complemento_usuario', 'Adicionar Complemento Usuario'), ('baseapp_detail_complemento_usuario', 'Visualizar Complemento Usuario'), ('baseapp_delete_complemento_usuario', 'Excluir Complemento Usuario'), ('baseapp_type_administrador', 'Tipo Administrador')),
            },
        ),
    ]
