# Generated by Django 3.2.9 on 2022-01-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complementousuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF.', max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
